### PR TITLE
Changes added imagelist preview to Tabs collection

### PR DESCRIPTION
**Pull request by srd-software**
Changes added imagelist preview to Tabs collection, as well as adding a way to update a few changes done in the IDE to be reflected immediately in the component on the form during design mode.

### CODE REVIEW

**Comment by Alexey-T** [comment]
I cannot apply this-- you overwrote the entire file attabs.pas. Pls make Pullreq so I see only your changes in diff.

**Comment by Alexey-T** [comment]
You placed attabs.pas into wrong folder. and 2nd file too. Place them over original files.

**Comment by Alexey-T** [comment]
applied with small changes. thanks

**Comment by srd-software** [comment]
Sorry about the file placement. First time I've tried to use github for this. Sounds like you were able to use it anyway? I'll try playing around with the github stuff again.

**Comment by srd-software** [comment]
OK, I placed them into the main folder on my side. Nothing has changed at this point other than I tried to get them into the right place!

Stan

________________________________

**Comment by Alexey-T** [comment]
I got the repo from GH and compared files by hand. merged. tks.

**Comment by Alexey-T** [comment]
Added "designide" to "requires" list.

**Comment by srd-software** [comment]
I have everything in a package and designide is in that, but yes, outside of a package it makes sense that it would need that added.

Stan

________________________________

**Comment by Alexey-T** [comment]
I overlooked it

**Comment by srd-software** [comment]
Alexey,

Couple of things I've found in DoPaintTabTo:

The following lines:
  if FOptShowFlat then //line 1272 in my IDE
    AColorBg:= ColorBg;

Prevent tab highlighting when flat. I'd prefer something like:

  if FOptShowFlat and (not FOptShowFlatHighLight) then
    AColorBg:= ColorBg;

That would take another property (e.g., "FOptShowFlatHighLight") but would allow the flat version to optionally highlight with mouseover like the non-flat tabs do.

Also, there seems to be an issue in the //borders section. The OptPosition property was not moving the active mark to top and bottom as I was thinking it should. I'll just paste in below what I did to correct the top and bottom options:

    if ATabActive then //line 1406 in my IDE
    begin
      C.Brush.Color:= ColorActiveMark;
      case FOptPosition of
        atpTop:
          //C.FillRect(Rect(PL2.X+2, ARect.Bottom-FOptActiveMarkSize, PR2.X, ARect.Bottom));
          C.FillRect(Rect(PL2.X+2, ARect.Top+1, PR2.X, ARect.Top+1+FOptActiveMarkSize));
        atpBottom:
          //C.FillRect(Rect(PL1.X+2, ARect.Top, PR1.X, ARect.Top+FOptActiveMarkSize));
          C.FillRect(Rect(PL2.X+2, ARect.Bottom-FOptActiveMarkSize, PR2.X, ARect.Bottom));
        atpLeft:
          //C.FillRect(Rect(ClientWidth-FOptActiveMarkSize, PR1.Y, ClientWidth, PR2.Y));
          C.FillRect(Rect(0, PL1.Y, FOptActiveMarkSize, PL2.Y));
        atpRight:
          //C.FillRect(Rect(0, PL1.Y, FOptActiveMarkSize, PL2.Y))
          C.FillRect(Rect(ClientWidth-FOptActiveMarkSize, PR1.Y, ClientWidth, PR2.Y));
       end;
    end;
  end

Now atpTop and atpBottom work as I was expecting.

I'd bet that the left and right should be switched as above, however, if using either of those options the whole tabset goes wonky and disappears. So there's something more involved with that and you'd be a lot better figuring out what that is. I wanted the atpTop to work and with the changes above it now does. And for now I just commented out the AColorBg:= ColorBg stuff so that mine will highlight when flat as I want it to.

BTW, I love this tab control. Roy Klever's "SmartTabs" are good if you need to put them on glass, and the tab control in the Jedi stuff works but it was never as simple to use as yours plus it added a lot of overhead to the exe.

If you want me to put all this into the github thing as an "issue" I can, but as you have seen I'm not real good with github yet!

Stan

________________________________

**Comment by Alexey-T** [comment]
Pls post as 2 new issues, not in here?

Pls use Markdown formatting for code blocks - 3 ticks

**Comment by srd-software** [comment]
OK, I put them in. Hopefully it's correct for the github system. If not let me know.

Stan

________________________________

**Pull request closed without merging**
