### PR TITLE
Index and Register fixes

### PR DESCRIPTION
**Pull request by srd-software**
OK, hopefully I have things in the right spot now! Index fix and register fix in this one.

### CODE REVIEW

**Comment by Alexey-T** [comment]
Must cache Getcomponent(index) to variable

**Comment by Alexey-T** [comment]
Add commit here to use this pull req

**Comment by srd-software** [comment]
> Must cache Getcomponent(index) to variable

Like this?
```
  aTab := nil;

  if GetComponent(Index) is TATTabData then
    aTab := TATTabData(GetComponent(Index));

  if aTab = nil then exit;

  if TATTabListCollection((aTab).Collection).AOwner is TATTabs then
  begin
    if TATTabs(TATTabListCollection((aTab).Collection).AOwner).Images <> nil then
    Result := TATTabs(TATTabListCollection((aTab).Collection).AOwner).Images;
    //debug use:
    //ShowMessage( FTabListCollection((GetComponent(Index) as TATTabData).Collection).AOwner.Name );
    exit;
  end;
```

**Comment by Alexey-T** [comment]
Yes, and no brackets around aTab

**Comment by srd-software** [comment]
Yeah, fixed that earlier when I saw it.

________________________________

**Comment by srd-software** [comment]
OK, not sure what "add commit here" means? Sorry, this github thing is hard for me to grasp!

________________________________

**Comment by srd-software** [comment]
Alexey, I have the component in my "big" app now (as opposed to the test app I've been using). It's working _very_ well. A bit more things to set up within the app itself but not nearly as hard as the Jedi control was, plus your component really looks good. Good job! So far no new issues or "showstopper" problems.

Image1

**Comment by Alexey-T** [comment]
Thanks for your patches. Your app looks good. Btw. Don't you want to port ATSynEdit to Delphi?

**Comment by srd-software** [comment]
I had to look up atsynedit, never saw that before. I didn't see any compiled demos so I installed lazarus this morning and then tried to compile things. I was only able to get the basic editor demo to work. Every other demo I tried was missing dependencies (generics.collections, flat controls, something called an econtrol, etc.). I got a lot of that put in but finally ran into one I couldn't get around; a call to "volitile" in at_sync I think it was. I commented that out just to move on and next it hiccuped on some thread call so I finally gave up on it for now. Since I was unable to get most of the underlying pieces to work in lazarus it would be very difficult (for me) to port!

I also found something called SynWrite which looks like a compiled version of the various pieces you've made. The text editor component used in that looks _very_ promising (as far as a syntax text component would go). So if that ever does get ported to delphi I'd love trying it out.

In the past I've used a component (delphi) called plusmemo. Nice and stable, and since it's VCL it compiles into the app, but I found it to be very slow on larger files. Then I moved to scintilla which is what the app above uses. It's a DLL which doesn't compile into the app (you can force it in but it's a pain). I don't like that I have to drag along a DLL with the exe but it works so well it's what I've been using most of the time. 

Is there some way to install all the pieces needed for atsynedit and its demos and required dependencies all at once? When I have more time I may try it all again anyway. For now I'm back working on the app above. Everything still seems great with the tabset!

**Comment by srd-software** [comment]
One question on atsynedit: it looks like it wants a monospaced font like courier. If I try to use arial, it tries to use it but it forces mono-spacing between chars. I tried setting pitch to variable but that didn't help. Is there some way to use a non-monospaced font (like arial) so that it displays correctly? My guess is it's not possible as it would throw all sorts of internal calculations off, but thought I'd ask.

**Comment by Alexey-T** [comment]
- Install .lpk package from https://github.com/Alexey-T/ATFlatControls
- Install package from https://github.com/Alexey-T/ATSynEdit
- open ATSynedit/app/demo_editor, it is enough to show editor.

(Don't get EControl and others)

**Comment by Alexey-T** [comment]
Non monospaces fonts are not suppoted (good question).
Let's continue in the ATSynedit repo issues. https://github.com/Alexey-T/ATSynEdit/issues/239

**Pull request merged**
