### PR TITLE
ImageIndex Fixes

### PR DESCRIPTION
**Pull request by srd-software**
Stop error if copying a tabset with images to another form that has no imagelist.

Ensure parent has images in the GetImageListAt in the register file.

### CODE REVIEW

**Comment by Alexey-T** [comment]
```
  begin
    if Brush.Color <> FColorBg then
      C.Brush.Color:= FColorBg;
  end;
```
missed "C." near Brush.color

---
2nd file in patch was added to wrong folder. see the DIFF here in the pull req.

**Comment by srd-software** [comment]
Yup, missed the "C", thanks for catching that.

**Comment by Alexey-T** [comment]
Delphi file duplicated

**Comment by srd-software** [comment]
I cleared out the last pull request and redid my github fork and did a new pull request. Hopefully that will clean things up.

Stan

________________________________

**Pull request closed without merging**
