### PR TITLE
* every tab can now have its own popup menu

### PR DESCRIPTION
**Pull request by DomenicoMammola**
Hi,
this is a small enhancement to allow adding a popup menu for every single tab. The popup menus can be defined in the TabData instance of every tab like we already do for captions and colors.

Domenico

### CODE REVIEW

**Comment by Alexey-T** [comment]
It is ok change. Tks. can I ask for a change?

a- no spaces before ":"
b- calc data via .GetTabData and save to D variable
c- test this D<>nil. use this D.TabPopupMenu.

**Comment by DomenicoMammola** [comment]
Hi Alexey,
sure, no problem at all.
I've modified the code as desired and I've made a commit to the branch. Can you please check if the changes are ok?
Thanks,
Domenico

**Comment by Alexey-T** [comment]
OK now, thanks.

**Comment by Alexey-T** [comment]
Pls modify method AddTab() too?

**Pull request merged**
