### PR TITLE
Add TabMenu var

### PR DESCRIPTION
**Pull request by srd-software**
Add public TabMenu var and small amount of code into ShowTabMenu so that user can assign their own TabMenu popup in their app.

### CODE REVIEW

**Comment by srd-software** [comment]
Thanks Alexey. Here's an image from my test app:

user tabmenu

**Comment by Alexey-T** [comment]
Looking good, nice patch

**Comment by Alexey-T** [comment]
You can try /user buttons 1...4/, also

**Comment by srd-software** [comment]
It does require a bit of code on the app side but it works well. I handle my own themes in my other app so that's where I really needed the extra var:

menubefore
menuthemed

**Comment by srd-software** [comment]
> You can try /user buttons 1...4/, also

Yes, those are very useful and I used 2 in the test app. The one with the "i" icon toggles between top and left tabset align, and the one with the "DX" icon toggles the tabset ShowFlat setting. I also have the painting working where each button highlights with mouseover, and the DX background color toggles on/off with ShowFlat state when the mouse is not over the button. 

I also have a small overlay icon on the DX button that follows ShowFlat state, although in actual use I'd choose either the color background or the icon to show the state, but not both. I plan to add those user buttons and functions into my "big" app soon as well (with more appropriate icons of course!).

Only tricky thing I ran into in TabDrawAfter was knowing when I was over a user button and which one it is (since the ATabIndex seems to be just for regular tabs). Finally came up with this:
```
  TabID := ATTabs1.GetTabAt(Arect.Left,ARect.Top,temp) ;

  if TabID = cTabIndexUser0 then...

  if TabID = cTabIndexUser1 then...
```
Image2
Image3

**Comment by Alexey-T** [comment]
Maybe you can add properties which control at what side to show colored bars?
OptSideOfColorMark (bool)
OptSideOfActiveMark (bool) for Flat mode only

**Comment by srd-software** [comment]
Properties for user button colored bars or for regular tabs?

**Comment by Alexey-T** [comment]
For regular tabs.

**Comment by Alexey-T** [comment]
Let's talk there
https://github.com/Alexey-T/ATTabs/issues/42

**Pull request merged**
