### PR TITLE
Added combobox to choose existing tab themes

### PR DESCRIPTION
**Pull request by srd-software**
Added combobox to choose existing tab themes

### CODE REVIEW

**Comment by Alexey-T** [comment]
- dir:= used in FormCreate and Combo click -- must use variable, calculate dir only once
- why keeping 2 buttons 'black' and 'blue'?

**Comment by srd-software** [comment]
Removed buttons, changed setting dir to one time.

**Comment by Alexey-T** [comment]
Little conflict with last fix (added FileName_Plus), pls solve

**Comment by Alexey-T** [comment]
I will solve it

**Comment by srd-software** [comment]
I reworked a few things in the delphi demo. Should I upload that or is that what you are working on now?

**Comment by Alexey-T** [comment]
That patch applied. You have new one? Ok

**Comment by srd-software** [comment]
What you have up there now is OK. No change.

**Pull request merged**
